In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

bureau = pd.read_csv('../input/home-credit-default-risk/bureau.csv')
bureau_balance = pd.read_csv('../input/home-credit-default-risk/bureau_balance.csv')

# Bureau

In [ ]:
bureau.shape

(1716428, 17)

In [ ]:
bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [ ]:
bureau['CREDIT_DAY_OVERDUE'].value_counts()

0       1712211
30          311
60          126
8           103
13          103
         ...
1445          1
278           1
707           1
2193          1
1931          1
Name: CREDIT_DAY_OVERDUE, Length: 942, dtype: int64

In [ ]:
bureau['CNT_CREDIT_PROLONG'].value_counts()

0    1707314
1       7620
2       1222
3        191
4         54
5         21
9          2
6          2
8          1
7          1
Name: CNT_CREDIT_PROLONG, dtype: int64

In [ ]:
bureau['AMT_CREDIT_SUM_OVERDUE'].value_counts()

0.000       1712270
4.500           301
9.000           107
13.500           81
18.000           72
             ...
323.010           1
88.695            1
142.830           1
5069.070          1
352.620           1
Name: AMT_CREDIT_SUM_OVERDUE, Length: 1616, dtype: int64

In [ ]:
# drop columns with more than 99% value is 0
bureau = bureau.drop(['CREDIT_DAY_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM_OVERDUE'], axis = 1)

In [ ]:
# drop columns with more than 60% null value
bureau = bureau.drop(['AMT_ANNUITY', 'AMT_CREDIT_MAX_OVERDUE'], axis = 1)

In [ ]:
# drop columns which is categoricate
bureau = bureau.drop(['CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'CREDIT_TYPE'], axis = 1)

In [ ]:
bureau.shape

(1716428, 9)

In [ ]:
bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,DAYS_CREDIT_UPDATE
0,215354,5714462,-497,-153.0,-153.0,91323.0,0.0,NaN,-131
1,215354,5714463,-208,1075.0,NaN,225000.0,171342.0,NaN,-20
2,215354,5714464,-203,528.0,NaN,464323.5,NaN,NaN,-16
3,215354,5714465,-203,NaN,NaN,90000.0,NaN,NaN,-16
4,215354,5714466,-629,1197.0,NaN,2700000.0,NaN,NaN,-21

In [ ]:
bureau.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'DAYS_CREDIT', 'DAYS_CREDIT_ENDDATE',
       'DAYS_ENDDATE_FACT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT',
       'AMT_CREDIT_SUM_LIMIT', 'DAYS_CREDIT_UPDATE'],
      dtype='object')

In [ ]:
bureau.to_csv('bureau_new.csv', index=False)

# Bureau Balance

In [ ]:
bureau_balance.shape

(27299925, 3)

In [ ]:
bureau_balance.columns

Index(['SK_ID_BUREAU', 'MONTHS_BALANCE', 'STATUS'], dtype='object')

In [ ]:
bureau_balance.to_csv('bureau_balance_new.csv', index=False)